FROM node:18-alpine as deps

WORKDIR /app

COPY . .

RUN apk add --update python3 make g++ protoc bash && rm -rf /var/cache/apk/*

RUN yarn global add node-gyp 

RUN chmod +x /app/packages/proto/gen_protos.sh

WORKDIR /app/packages/proto

RUN yarn install --frozen-lockfile

RUN yarn build

WORKDIR /app

RUN yarn install --frozen-lockfile --ignore-scripts

FROM node:18 as api-gateway-dev

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules/

COPY --from=deps /app/packages/api-gateway/node_modules ./packages/node_modules/

COPY . .

COPY --from=deps /app/packages/proto/ ./packages/proto/

WORKDIR /app/packages/api-gateway

FROM node:18 as auth-service-dev

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules/

COPY --from=deps /app/packages/auth-service/node_modules ./packages/node_modules/

COPY . .

COPY --from=deps /app/packages/proto/ ./packages/proto/

WORKDIR /app/packages/auth-service

FROM node:18 as db-service-dev

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules/

COPY --from=deps /app/packages/db-service/node_modules ./packages/node_modules/

COPY . .

COPY --from=deps /app/packages/proto/ ./packages/proto/

WORKDIR /app/packages/db-service

RUN yarn prisma generate
