services:
  api-gateway:
    extends:
      file: docker-compose-dev.yml
      service: api-gateway
    volumes:
      - ./packages/api-gateway:/app/packages/api-gateway
      - /app/packages/api-gateway/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/api-gateway/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  auth-service:
    extends:
      file: docker-compose-dev.yml
      service: auth-service
    volumes:
      - ./packages/auth-service:/app/packages/auth-service
      - /app/packages/auth-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/auth-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  email-service:
    extends:
      file: docker-compose-dev.yml
      service: email-service
    volumes:
      - ./packages/email-service:/app/packages/email-service
      - /app/packages/email-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/email-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  file-service:
    extends:
      file: docker-compose-dev.yml
      service: file-service
    volumes:
      - ./packages/file-service:/app/packages/file-service
      - /app/packages/file-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/file-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  analytics-service:
    extends:
      file: docker-compose-dev.yml
      service: analytics-service
    volumes:
      - ./packages/analytics-service:/app/packages/analytics-service
      - /app/packages/analytics-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/analytics-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  logging-service:
    extends:
      file: docker-compose-dev.yml
      service: logging-service
    volumes:
      - ./packages/logging-service:/app/packages/logging-service
      - /app/packages/logging-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/logging-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  db-service:
    extends:
      file: docker-compose-dev.yml
      service: db-service
    volumes:
      - ./packages/db-service:/app/packages/db-service
      - /app/packages/db-service/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./packages/db-service/package.json
        - action: rebuild
          path: ./Dockerfile.dev

  db:
    extends:
      file: docker-compose-dev.yml
      service: db
