FROM juno/deps AS deps

FROM node:18 as auth-service 

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules/

COPY --from=deps /app/packages/auth-service/node_modules ./packages/node_modules/

COPY . .

WORKDIR /app/packages/auth-service

CMD ["yarn", "start:prod"]
